// lib/avatars-lista.js — GENERADO. No editar a mano.
//
// Lo escribe `scripts/generar-avatares.mjs`. Aquí solo va la LISTA; los dibujos
// son archivos en `public/avatars/` y se piden por `<img src>`, porque los 96
// juntos pesan 537 KB y nadie tiene que descargarlos para ver la cabecera.

export const AVATAR_CATEGORIES = [
  { id: 'avataaars', nombre: 'Caras' },
  { id: 'peeps', nombre: 'Retratos' },
  { id: 'notion', nombre: 'Trazo' },
  { id: 'lorelei', nombre: 'Ilustradas' },
  { id: 'bottts', nombre: 'Robots' },
  { id: 'thumbs', nombre: 'Caritas' },
  { id: 'shapes', nombre: 'Formas' },
  { id: 'glass', nombre: 'Degradados' },
]

export const AVATARS = [
  { id: 'avataaars-1', nombre: 'Caras 1', categoria: 'avataaars' },
  { id: 'avataaars-2', nombre: 'Caras 2', categoria: 'avataaars' },
  { id: 'avataaars-3', nombre: 'Caras 3', categoria: 'avataaars' },
  { id: 'avataaars-4', nombre: 'Caras 4', categoria: 'avataaars' },
  { id: 'avataaars-5', nombre: 'Caras 5', categoria: 'avataaars' },
  { id: 'avataaars-6', nombre: 'Caras 6', categoria: 'avataaars' },
  { id: 'avataaars-7', nombre: 'Caras 7', categoria: 'avataaars' },
  { id: 'avataaars-8', nombre: 'Caras 8', categoria: 'avataaars' },
  { id: 'avataaars-9', nombre: 'Caras 9', categoria: 'avataaars' },
  { id: 'avataaars-10', nombre: 'Caras 10', categoria: 'avataaars' },
  { id: 'avataaars-11', nombre: 'Caras 11', categoria: 'avataaars' },
  { id: 'avataaars-12', nombre: 'Caras 12', categoria: 'avataaars' },
  { id: 'peeps-1', nombre: 'Retratos 1', categoria: 'peeps' },
  { id: 'peeps-2', nombre: 'Retratos 2', categoria: 'peeps' },
  { id: 'peeps-3', nombre: 'Retratos 3', categoria: 'peeps' },
  { id: 'peeps-4', nombre: 'Retratos 4', categoria: 'peeps' },
  { id: 'peeps-5', nombre: 'Retratos 5', categoria: 'peeps' },
  { id: 'peeps-6', nombre: 'Retratos 6', categoria: 'peeps' },
  { id: 'peeps-7', nombre: 'Retratos 7', categoria: 'peeps' },
  { id: 'peeps-8', nombre: 'Retratos 8', categoria: 'peeps' },
  { id: 'peeps-9', nombre: 'Retratos 9', categoria: 'peeps' },
  { id: 'peeps-10', nombre: 'Retratos 10', categoria: 'peeps' },
  { id: 'peeps-11', nombre: 'Retratos 11', categoria: 'peeps' },
  { id: 'peeps-12', nombre: 'Retratos 12', categoria: 'peeps' },
  { id: 'notion-1', nombre: 'Trazo 1', categoria: 'notion' },
  { id: 'notion-2', nombre: 'Trazo 2', categoria: 'notion' },
  { id: 'notion-3', nombre: 'Trazo 3', categoria: 'notion' },
  { id: 'notion-4', nombre: 'Trazo 4', categoria: 'notion' },
  { id: 'notion-5', nombre: 'Trazo 5', categoria: 'notion' },
  { id: 'notion-6', nombre: 'Trazo 6', categoria: 'notion' },
  { id: 'notion-7', nombre: 'Trazo 7', categoria: 'notion' },
  { id: 'notion-8', nombre: 'Trazo 8', categoria: 'notion' },
  { id: 'notion-9', nombre: 'Trazo 9', categoria: 'notion' },
  { id: 'notion-10', nombre: 'Trazo 10', categoria: 'notion' },
  { id: 'notion-11', nombre: 'Trazo 11', categoria: 'notion' },
  { id: 'notion-12', nombre: 'Trazo 12', categoria: 'notion' },
  { id: 'lorelei-1', nombre: 'Ilustradas 1', categoria: 'lorelei' },
  { id: 'lorelei-2', nombre: 'Ilustradas 2', categoria: 'lorelei' },
  { id: 'lorelei-3', nombre: 'Ilustradas 3', categoria: 'lorelei' },
  { id: 'lorelei-4', nombre: 'Ilustradas 4', categoria: 'lorelei' },
  { id: 'lorelei-5', nombre: 'Ilustradas 5', categoria: 'lorelei' },
  { id: 'lorelei-6', nombre: 'Ilustradas 6', categoria: 'lorelei' },
  { id: 'lorelei-7', nombre: 'Ilustradas 7', categoria: 'lorelei' },
  { id: 'lorelei-8', nombre: 'Ilustradas 8', categoria: 'lorelei' },
  { id: 'lorelei-9', nombre: 'Ilustradas 9', categoria: 'lorelei' },
  { id: 'lorelei-10', nombre: 'Ilustradas 10', categoria: 'lorelei' },
  { id: 'lorelei-11', nombre: 'Ilustradas 11', categoria: 'lorelei' },
  { id: 'lorelei-12', nombre: 'Ilustradas 12', categoria: 'lorelei' },
  { id: 'bottts-1', nombre: 'Robots 1', categoria: 'bottts' },
  { id: 'bottts-2', nombre: 'Robots 2', categoria: 'bottts' },
  { id: 'bottts-3', nombre: 'Robots 3', categoria: 'bottts' },
  { id: 'bottts-4', nombre: 'Robots 4', categoria: 'bottts' },
  { id: 'bottts-5', nombre: 'Robots 5', categoria: 'bottts' },
  { id: 'bottts-6', nombre: 'Robots 6', categoria: 'bottts' },
  { id: 'bottts-7', nombre: 'Robots 7', categoria: 'bottts' },
  { id: 'bottts-8', nombre: 'Robots 8', categoria: 'bottts' },
  { id: 'bottts-9', nombre: 'Robots 9', categoria: 'bottts' },
  { id: 'bottts-10', nombre: 'Robots 10', categoria: 'bottts' },
  { id: 'bottts-11', nombre: 'Robots 11', categoria: 'bottts' },
  { id: 'bottts-12', nombre: 'Robots 12', categoria: 'bottts' },
  { id: 'thumbs-1', nombre: 'Caritas 1', categoria: 'thumbs' },
  { id: 'thumbs-2', nombre: 'Caritas 2', categoria: 'thumbs' },
  { id: 'thumbs-3', nombre: 'Caritas 3', categoria: 'thumbs' },
  { id: 'thumbs-4', nombre: 'Caritas 4', categoria: 'thumbs' },
  { id: 'thumbs-5', nombre: 'Caritas 5', categoria: 'thumbs' },
  { id: 'thumbs-6', nombre: 'Caritas 6', categoria: 'thumbs' },
  { id: 'thumbs-7', nombre: 'Caritas 7', categoria: 'thumbs' },
  { id: 'thumbs-8', nombre: 'Caritas 8', categoria: 'thumbs' },
  { id: 'thumbs-9', nombre: 'Caritas 9', categoria: 'thumbs' },
  { id: 'thumbs-10', nombre: 'Caritas 10', categoria: 'thumbs' },
  { id: 'thumbs-11', nombre: 'Caritas 11', categoria: 'thumbs' },
  { id: 'thumbs-12', nombre: 'Caritas 12', categoria: 'thumbs' },
  { id: 'shapes-1', nombre: 'Formas 1', categoria: 'shapes' },
  { id: 'shapes-2', nombre: 'Formas 2', categoria: 'shapes' },
  { id: 'shapes-3', nombre: 'Formas 3', categoria: 'shapes' },
  { id: 'shapes-4', nombre: 'Formas 4', categoria: 'shapes' },
  { id: 'shapes-5', nombre: 'Formas 5', categoria: 'shapes' },
  { id: 'shapes-6', nombre: 'Formas 6', categoria: 'shapes' },
  { id: 'shapes-7', nombre: 'Formas 7', categoria: 'shapes' },
  { id: 'shapes-8', nombre: 'Formas 8', categoria: 'shapes' },
  { id: 'shapes-9', nombre: 'Formas 9', categoria: 'shapes' },
  { id: 'shapes-10', nombre: 'Formas 10', categoria: 'shapes' },
  { id: 'shapes-11', nombre: 'Formas 11', categoria: 'shapes' },
  { id: 'shapes-12', nombre: 'Formas 12', categoria: 'shapes' },
  { id: 'glass-1', nombre: 'Degradados 1', categoria: 'glass' },
  { id: 'glass-2', nombre: 'Degradados 2', categoria: 'glass' },
  { id: 'glass-3', nombre: 'Degradados 3', categoria: 'glass' },
  { id: 'glass-4', nombre: 'Degradados 4', categoria: 'glass' },
  { id: 'glass-5', nombre: 'Degradados 5', categoria: 'glass' },
  { id: 'glass-6', nombre: 'Degradados 6', categoria: 'glass' },
  { id: 'glass-7', nombre: 'Degradados 7', categoria: 'glass' },
  { id: 'glass-8', nombre: 'Degradados 8', categoria: 'glass' },
  { id: 'glass-9', nombre: 'Degradados 9', categoria: 'glass' },
  { id: 'glass-10', nombre: 'Degradados 10', categoria: 'glass' },
  { id: 'glass-11', nombre: 'Degradados 11', categoria: 'glass' },
  { id: 'glass-12', nombre: 'Degradados 12', categoria: 'glass' },
]
