// lib/avatars-lista.js — GENERADO. No editar a mano.
//
// Lo escribe `scripts/generar-avatares.mjs`. Aquí solo va la LISTA; los dibujos
// son archivos en `public/avatars/` y se piden por `<img src>`, porque los
// 144 juntos pesan 633 KB y nadie tiene que descargarlos para ver la cabecera.

export const AVATAR_CATEGORIES = [
  { id: 'caras', nombre: 'Caras' },
  { id: 'rostro', nombre: 'Solo cara' },
  { id: 'trazo', nombre: 'Trazo' },
  { id: 'caritas', nombre: 'Caritas' },
  { id: 'robots', nombre: 'Robots' },
  { id: 'geek', nombre: 'Geek' },
  { id: 'dinero', nombre: 'Dinero' },
  { id: 'premios', nombre: 'Premios' },
  { id: 'gestos', nombre: 'Gestos' },
  { id: 'sonrisas', nombre: 'Sonrisas' },
  { id: 'garabatos', nombre: 'Garabatos' },
  { id: 'retratos', nombre: 'Retratos' },
]

export const AVATARS = [
  { id: 'caras-1', nombre: 'Caras 1', categoria: 'caras' },
  { id: 'caras-2', nombre: 'Caras 2', categoria: 'caras' },
  { id: 'caras-3', nombre: 'Caras 3', categoria: 'caras' },
  { id: 'caras-4', nombre: 'Caras 4', categoria: 'caras' },
  { id: 'caras-5', nombre: 'Caras 5', categoria: 'caras' },
  { id: 'caras-6', nombre: 'Caras 6', categoria: 'caras' },
  { id: 'caras-7', nombre: 'Caras 7', categoria: 'caras' },
  { id: 'caras-8', nombre: 'Caras 8', categoria: 'caras' },
  { id: 'caras-9', nombre: 'Caras 9', categoria: 'caras' },
  { id: 'caras-10', nombre: 'Caras 10', categoria: 'caras' },
  { id: 'caras-11', nombre: 'Caras 11', categoria: 'caras' },
  { id: 'caras-12', nombre: 'Caras 12', categoria: 'caras' },
  { id: 'rostro-1', nombre: 'Solo cara 1', categoria: 'rostro' },
  { id: 'rostro-2', nombre: 'Solo cara 2', categoria: 'rostro' },
  { id: 'rostro-3', nombre: 'Solo cara 3', categoria: 'rostro' },
  { id: 'rostro-4', nombre: 'Solo cara 4', categoria: 'rostro' },
  { id: 'rostro-5', nombre: 'Solo cara 5', categoria: 'rostro' },
  { id: 'rostro-6', nombre: 'Solo cara 6', categoria: 'rostro' },
  { id: 'rostro-7', nombre: 'Solo cara 7', categoria: 'rostro' },
  { id: 'rostro-8', nombre: 'Solo cara 8', categoria: 'rostro' },
  { id: 'rostro-9', nombre: 'Solo cara 9', categoria: 'rostro' },
  { id: 'rostro-10', nombre: 'Solo cara 10', categoria: 'rostro' },
  { id: 'rostro-11', nombre: 'Solo cara 11', categoria: 'rostro' },
  { id: 'rostro-12', nombre: 'Solo cara 12', categoria: 'rostro' },
  { id: 'trazo-1', nombre: 'Trazo 1', categoria: 'trazo' },
  { id: 'trazo-2', nombre: 'Trazo 2', categoria: 'trazo' },
  { id: 'trazo-3', nombre: 'Trazo 3', categoria: 'trazo' },
  { id: 'trazo-4', nombre: 'Trazo 4', categoria: 'trazo' },
  { id: 'trazo-5', nombre: 'Trazo 5', categoria: 'trazo' },
  { id: 'trazo-6', nombre: 'Trazo 6', categoria: 'trazo' },
  { id: 'trazo-7', nombre: 'Trazo 7', categoria: 'trazo' },
  { id: 'trazo-8', nombre: 'Trazo 8', categoria: 'trazo' },
  { id: 'trazo-9', nombre: 'Trazo 9', categoria: 'trazo' },
  { id: 'trazo-10', nombre: 'Trazo 10', categoria: 'trazo' },
  { id: 'trazo-11', nombre: 'Trazo 11', categoria: 'trazo' },
  { id: 'trazo-12', nombre: 'Trazo 12', categoria: 'trazo' },
  { id: 'caritas-1', nombre: 'Caritas 1', categoria: 'caritas' },
  { id: 'caritas-2', nombre: 'Caritas 2', categoria: 'caritas' },
  { id: 'caritas-3', nombre: 'Caritas 3', categoria: 'caritas' },
  { id: 'caritas-4', nombre: 'Caritas 4', categoria: 'caritas' },
  { id: 'caritas-5', nombre: 'Caritas 5', categoria: 'caritas' },
  { id: 'caritas-6', nombre: 'Caritas 6', categoria: 'caritas' },
  { id: 'caritas-7', nombre: 'Caritas 7', categoria: 'caritas' },
  { id: 'caritas-8', nombre: 'Caritas 8', categoria: 'caritas' },
  { id: 'caritas-9', nombre: 'Caritas 9', categoria: 'caritas' },
  { id: 'caritas-10', nombre: 'Caritas 10', categoria: 'caritas' },
  { id: 'caritas-11', nombre: 'Caritas 11', categoria: 'caritas' },
  { id: 'caritas-12', nombre: 'Caritas 12', categoria: 'caritas' },
  { id: 'robots-1', nombre: 'Robots 1', categoria: 'robots' },
  { id: 'robots-2', nombre: 'Robots 2', categoria: 'robots' },
  { id: 'robots-3', nombre: 'Robots 3', categoria: 'robots' },
  { id: 'robots-4', nombre: 'Robots 4', categoria: 'robots' },
  { id: 'robots-5', nombre: 'Robots 5', categoria: 'robots' },
  { id: 'robots-6', nombre: 'Robots 6', categoria: 'robots' },
  { id: 'robots-7', nombre: 'Robots 7', categoria: 'robots' },
  { id: 'robots-8', nombre: 'Robots 8', categoria: 'robots' },
  { id: 'robots-9', nombre: 'Robots 9', categoria: 'robots' },
  { id: 'robots-10', nombre: 'Robots 10', categoria: 'robots' },
  { id: 'robots-11', nombre: 'Robots 11', categoria: 'robots' },
  { id: 'robots-12', nombre: 'Robots 12', categoria: 'robots' },
  { id: 'geek-1', nombre: 'Geek 1', categoria: 'geek' },
  { id: 'geek-2', nombre: 'Geek 2', categoria: 'geek' },
  { id: 'geek-3', nombre: 'Geek 3', categoria: 'geek' },
  { id: 'geek-4', nombre: 'Geek 4', categoria: 'geek' },
  { id: 'geek-5', nombre: 'Geek 5', categoria: 'geek' },
  { id: 'geek-6', nombre: 'Geek 6', categoria: 'geek' },
  { id: 'geek-7', nombre: 'Geek 7', categoria: 'geek' },
  { id: 'geek-8', nombre: 'Geek 8', categoria: 'geek' },
  { id: 'geek-9', nombre: 'Geek 9', categoria: 'geek' },
  { id: 'geek-10', nombre: 'Geek 10', categoria: 'geek' },
  { id: 'geek-11', nombre: 'Geek 11', categoria: 'geek' },
  { id: 'geek-12', nombre: 'Geek 12', categoria: 'geek' },
  { id: 'dinero-1', nombre: 'Dinero 1', categoria: 'dinero' },
  { id: 'dinero-2', nombre: 'Dinero 2', categoria: 'dinero' },
  { id: 'dinero-3', nombre: 'Dinero 3', categoria: 'dinero' },
  { id: 'dinero-4', nombre: 'Dinero 4', categoria: 'dinero' },
  { id: 'dinero-5', nombre: 'Dinero 5', categoria: 'dinero' },
  { id: 'dinero-6', nombre: 'Dinero 6', categoria: 'dinero' },
  { id: 'dinero-7', nombre: 'Dinero 7', categoria: 'dinero' },
  { id: 'dinero-8', nombre: 'Dinero 8', categoria: 'dinero' },
  { id: 'dinero-9', nombre: 'Dinero 9', categoria: 'dinero' },
  { id: 'dinero-10', nombre: 'Dinero 10', categoria: 'dinero' },
  { id: 'dinero-11', nombre: 'Dinero 11', categoria: 'dinero' },
  { id: 'dinero-12', nombre: 'Dinero 12', categoria: 'dinero' },
  { id: 'premios-1', nombre: 'Premios 1', categoria: 'premios' },
  { id: 'premios-2', nombre: 'Premios 2', categoria: 'premios' },
  { id: 'premios-3', nombre: 'Premios 3', categoria: 'premios' },
  { id: 'premios-4', nombre: 'Premios 4', categoria: 'premios' },
  { id: 'premios-5', nombre: 'Premios 5', categoria: 'premios' },
  { id: 'premios-6', nombre: 'Premios 6', categoria: 'premios' },
  { id: 'premios-7', nombre: 'Premios 7', categoria: 'premios' },
  { id: 'premios-8', nombre: 'Premios 8', categoria: 'premios' },
  { id: 'premios-9', nombre: 'Premios 9', categoria: 'premios' },
  { id: 'premios-10', nombre: 'Premios 10', categoria: 'premios' },
  { id: 'premios-11', nombre: 'Premios 11', categoria: 'premios' },
  { id: 'premios-12', nombre: 'Premios 12', categoria: 'premios' },
  { id: 'gestos-1', nombre: 'Gestos 1', categoria: 'gestos' },
  { id: 'gestos-2', nombre: 'Gestos 2', categoria: 'gestos' },
  { id: 'gestos-3', nombre: 'Gestos 3', categoria: 'gestos' },
  { id: 'gestos-4', nombre: 'Gestos 4', categoria: 'gestos' },
  { id: 'gestos-5', nombre: 'Gestos 5', categoria: 'gestos' },
  { id: 'gestos-6', nombre: 'Gestos 6', categoria: 'gestos' },
  { id: 'gestos-7', nombre: 'Gestos 7', categoria: 'gestos' },
  { id: 'gestos-8', nombre: 'Gestos 8', categoria: 'gestos' },
  { id: 'gestos-9', nombre: 'Gestos 9', categoria: 'gestos' },
  { id: 'gestos-10', nombre: 'Gestos 10', categoria: 'gestos' },
  { id: 'gestos-11', nombre: 'Gestos 11', categoria: 'gestos' },
  { id: 'gestos-12', nombre: 'Gestos 12', categoria: 'gestos' },
  { id: 'sonrisas-1', nombre: 'Sonrisas 1', categoria: 'sonrisas' },
  { id: 'sonrisas-2', nombre: 'Sonrisas 2', categoria: 'sonrisas' },
  { id: 'sonrisas-3', nombre: 'Sonrisas 3', categoria: 'sonrisas' },
  { id: 'sonrisas-4', nombre: 'Sonrisas 4', categoria: 'sonrisas' },
  { id: 'sonrisas-5', nombre: 'Sonrisas 5', categoria: 'sonrisas' },
  { id: 'sonrisas-6', nombre: 'Sonrisas 6', categoria: 'sonrisas' },
  { id: 'sonrisas-7', nombre: 'Sonrisas 7', categoria: 'sonrisas' },
  { id: 'sonrisas-8', nombre: 'Sonrisas 8', categoria: 'sonrisas' },
  { id: 'sonrisas-9', nombre: 'Sonrisas 9', categoria: 'sonrisas' },
  { id: 'sonrisas-10', nombre: 'Sonrisas 10', categoria: 'sonrisas' },
  { id: 'sonrisas-11', nombre: 'Sonrisas 11', categoria: 'sonrisas' },
  { id: 'sonrisas-12', nombre: 'Sonrisas 12', categoria: 'sonrisas' },
  { id: 'garabatos-1', nombre: 'Garabatos 1', categoria: 'garabatos' },
  { id: 'garabatos-2', nombre: 'Garabatos 2', categoria: 'garabatos' },
  { id: 'garabatos-3', nombre: 'Garabatos 3', categoria: 'garabatos' },
  { id: 'garabatos-4', nombre: 'Garabatos 4', categoria: 'garabatos' },
  { id: 'garabatos-5', nombre: 'Garabatos 5', categoria: 'garabatos' },
  { id: 'garabatos-6', nombre: 'Garabatos 6', categoria: 'garabatos' },
  { id: 'garabatos-7', nombre: 'Garabatos 7', categoria: 'garabatos' },
  { id: 'garabatos-8', nombre: 'Garabatos 8', categoria: 'garabatos' },
  { id: 'garabatos-9', nombre: 'Garabatos 9', categoria: 'garabatos' },
  { id: 'garabatos-10', nombre: 'Garabatos 10', categoria: 'garabatos' },
  { id: 'garabatos-11', nombre: 'Garabatos 11', categoria: 'garabatos' },
  { id: 'garabatos-12', nombre: 'Garabatos 12', categoria: 'garabatos' },
  { id: 'retratos-1', nombre: 'Retratos 1', categoria: 'retratos' },
  { id: 'retratos-2', nombre: 'Retratos 2', categoria: 'retratos' },
  { id: 'retratos-3', nombre: 'Retratos 3', categoria: 'retratos' },
  { id: 'retratos-4', nombre: 'Retratos 4', categoria: 'retratos' },
  { id: 'retratos-5', nombre: 'Retratos 5', categoria: 'retratos' },
  { id: 'retratos-6', nombre: 'Retratos 6', categoria: 'retratos' },
  { id: 'retratos-7', nombre: 'Retratos 7', categoria: 'retratos' },
  { id: 'retratos-8', nombre: 'Retratos 8', categoria: 'retratos' },
  { id: 'retratos-9', nombre: 'Retratos 9', categoria: 'retratos' },
  { id: 'retratos-10', nombre: 'Retratos 10', categoria: 'retratos' },
  { id: 'retratos-11', nombre: 'Retratos 11', categoria: 'retratos' },
  { id: 'retratos-12', nombre: 'Retratos 12', categoria: 'retratos' },
]
