// lib/countries.js — Diccionario central de configuracion por pais
// Fuente unica de verdad para moneda, timezone, validaciones, etc.
// Agregar un pais nuevo = agregar una entrada aqui. Sin migraciones de BD.

export const COUNTRIES = {
  co: {
    name: 'Colombia',
    currency: 'COP',
    currencySymbol: '$',
    currencyDecimals: 0,
    locale: 'es-CO',
    timezone: 'America/Bogota',
    utcOffset: -5,
    phonePrefix: '+57',
    phoneRegex: /^3\d{9}$/,
    phoneDigits: 10,
    phonePlaceholder: '3001234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{6,12}$/,
    documentLabel: 'Cédula',
    documentAbbr: 'CC',
    documentPlaceholder: '1023456789',
    roundingUnit: 100,
    paymentGateway: 'mercadopago',
    speechLang: 'es-CO',
    dateFormat: 'DD/MM/YYYY',
  },
  mx: {
    name: 'Mexico',
    currency: 'MXN',
    currencySymbol: '$',
    currencyDecimals: 0,
    locale: 'es-MX',
    timezone: 'America/Mexico_City',
    utcOffset: -6,
    timezones: ['America/Mexico_City', 'America/Cancun', 'America/Chihuahua', 'America/Tijuana'],
    phonePrefix: '+52',
    phoneRegex: /^\d{10}$/,
    phoneDigits: 10,
    phonePlaceholder: '5512345678',
    phoneLabel: 'Celular',
    documentRegex: /^[A-Z]{4}\d{6}[A-Z0-9]{8}$|^\d{10,18}$/i,
    documentLabel: 'CURP / INE',
    documentAbbr: 'CURP',
    documentPlaceholder: 'CURP o número de INE',
    roundingUnit: 10,
    paymentGateway: 'mercadopago',
    speechLang: 'es-MX',
    dateFormat: 'DD/MM/YYYY',
  },
  pe: {
    name: 'Peru',
    currency: 'PEN',
    currencySymbol: 'S/',
    currencyDecimals: 2,
    locale: 'es-PE',
    timezone: 'America/Lima',
    utcOffset: -5,
    phonePrefix: '+51',
    phoneRegex: /^9\d{8}$/,
    phoneDigits: 9,
    phonePlaceholder: '912345678',
    phoneLabel: 'Celular',
    documentRegex: /^\d{8}$/,
    documentLabel: 'DNI',
    documentAbbr: 'DNI',
    documentPlaceholder: '12345678',
    roundingUnit: 1,
    paymentGateway: 'mercadopago',
    speechLang: 'es-PE',
    dateFormat: 'DD/MM/YYYY',
  },
  ec: {
    name: 'Ecuador',
    currency: 'USD',
    currencySymbol: '$',
    currencyDecimals: 2,
    locale: 'es-EC',
    timezone: 'America/Guayaquil',
    utcOffset: -5,
    phonePrefix: '+593',
    phoneRegex: /^0?9\d{8}$/,
    phoneDigits: 10,
    phonePlaceholder: '0991234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{10}$/,
    documentLabel: 'Cédula',
    documentAbbr: 'CI',
    documentPlaceholder: '1712345678',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-EC',
    dateFormat: 'DD/MM/YYYY',
  },
  do: {
    name: 'Republica Dominicana',
    currency: 'DOP',
    currencySymbol: 'RD$',
    currencyDecimals: 0,
    locale: 'es-DO',
    timezone: 'America/Santo_Domingo',
    utcOffset: -4,
    phonePrefix: '+1',
    phoneRegex: /^[89]\d{9}$/,
    phoneDigits: 10,
    phonePlaceholder: '8091234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{11}$/,
    documentLabel: 'Cédula',
    documentAbbr: 'CI',
    documentPlaceholder: '00112345678',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-DO',
    dateFormat: 'DD/MM/YYYY',
  },
  ve: {
    name: 'Venezuela',
    currency: 'USD',
    currencySymbol: '$',
    currencyDecimals: 2,
    locale: 'es-VE',
    timezone: 'America/Caracas',
    utcOffset: -4,
    phonePrefix: '+58',
    phoneRegex: /^(04|4)\d{9,10}$/,
    phoneDigits: 11,
    phonePlaceholder: '04121234567',
    phoneLabel: 'Celular',
    documentRegex: /^[VEJPvejp]-?\d{6,9}$/,
    documentLabel: 'Cédula (V/E/J)',
    documentAbbr: 'CI',
    documentPlaceholder: 'V-12345678',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-VE',
    dateFormat: 'DD/MM/YYYY',
  },
  hn: {
    name: 'Honduras',
    currency: 'HNL',
    currencySymbol: 'L',
    currencyDecimals: 0,
    locale: 'es-HN',
    timezone: 'America/Tegucigalpa',
    utcOffset: -6,
    phonePrefix: '+504',
    phoneRegex: /^\d{8}$/,
    phoneDigits: 8,
    phonePlaceholder: '91234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{4}-?\d{4}-?\d{5}$/,
    documentLabel: 'Identidad',
    documentAbbr: 'ID',
    documentPlaceholder: '0101-1990-12345',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-HN',
    dateFormat: 'DD/MM/YYYY',
  },
  gt: {
    name: 'Guatemala',
    currency: 'GTQ',
    currencySymbol: 'Q',
    currencyDecimals: 0,
    locale: 'es-GT',
    timezone: 'America/Guatemala',
    utcOffset: -6,
    phonePrefix: '+502',
    phoneRegex: /^\d{8}$/,
    phoneDigits: 8,
    phonePlaceholder: '51234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{4,13}$/,
    documentLabel: 'DPI',
    documentAbbr: 'DPI',
    documentPlaceholder: '1234567890101',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-GT',
    dateFormat: 'DD/MM/YYYY',
  },
  sv: {
    name: 'El Salvador',
    currency: 'USD',
    currencySymbol: '$',
    currencyDecimals: 2,
    locale: 'es-SV',
    timezone: 'America/El_Salvador',
    utcOffset: -6,
    phonePrefix: '+503',
    phoneRegex: /^\d{8}$/,
    phoneDigits: 8,
    phonePlaceholder: '71234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{8,9}$/,
    documentLabel: 'DUI',
    documentAbbr: 'DUI',
    documentPlaceholder: '012345678',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-SV',
    dateFormat: 'DD/MM/YYYY',
  },
  ni: {
    name: 'Nicaragua',
    currency: 'NIO',
    currencySymbol: 'C$',
    currencyDecimals: 0,
    locale: 'es-NI',
    timezone: 'America/Managua',
    utcOffset: -6,
    phonePrefix: '+505',
    phoneRegex: /^\d{8}$/,
    phoneDigits: 8,
    phonePlaceholder: '81234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{3}-?\d{6}-?\d{4}[A-Za-z]$/,
    documentLabel: 'Cédula',
    documentAbbr: 'CI',
    documentPlaceholder: '001-010190-0001A',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-NI',
    dateFormat: 'DD/MM/YYYY',
  },
  pa: {
    name: 'Panama',
    currency: 'USD',
    currencySymbol: '$',
    currencyDecimals: 2,
    locale: 'es-PA',
    timezone: 'America/Panama',
    utcOffset: -5,
    phonePrefix: '+507',
    phoneRegex: /^6\d{7}$/,
    phoneDigits: 8,
    phonePlaceholder: '61234567',
    phoneLabel: 'Celular',
    documentRegex: /^(PE|E|N|[23456789]|1[0123]|10)-?\d{1,4}-?\d{1,6}$/i,
    documentLabel: 'Cédula',
    documentAbbr: 'CI',
    documentPlaceholder: '8-123-4567',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-PA',
    dateFormat: 'DD/MM/YYYY',
  },
  cr: {
    name: 'Costa Rica',
    currency: 'CRC',
    currencySymbol: '₡',
    currencyDecimals: 0,
    locale: 'es-CR',
    timezone: 'America/Costa_Rica',
    utcOffset: -6,
    phonePrefix: '+506',
    phoneRegex: /^\d{8}$/,
    phoneDigits: 8,
    phonePlaceholder: '61234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{9,12}$/,
    documentLabel: 'Cédula',
    documentAbbr: 'CI',
    documentPlaceholder: '123456789',
    roundingUnit: 100,
    paymentGateway: 'manual',
    speechLang: 'es-CR',
    dateFormat: 'DD/MM/YYYY',
  },
  us: {
    name: 'Estados Unidos',
    currency: 'USD',
    currencySymbol: '$',
    currencyDecimals: 2,
    locale: 'es-US',
    timezone: 'America/New_York',
    utcOffset: -5,
    timezones: ['America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles'],
    phonePrefix: '+1',
    phoneRegex: /^\d{10}$/,
    phoneDigits: 10,
    phonePlaceholder: '2125551234',
    phoneLabel: 'Celular',
    documentRegex: /^.{4,20}$/,
    documentLabel: 'ID / Documento',
    documentAbbr: 'ID',
    documentPlaceholder: 'SSN, ITIN o ID estatal',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-US',
    dateFormat: 'MM/DD/YYYY',
  },
}

export const COUNTRY_CODES = Object.keys(COUNTRIES)
export const DEFAULT_COUNTRY = 'co'

export function getCountryConfig(country) {
  return COUNTRIES[country] || COUNTRIES[DEFAULT_COUNTRY]
}

export function getCountryList() {
  return COUNTRY_CODES.map((code) => ({
    code,
    name: COUNTRIES[code].name,
  }))
}
