// lib/countries.js — Diccionario central de configuracion por pais
// Fuente unica de verdad para moneda, timezone, validaciones, etc.
// Agregar un pais nuevo = agregar una entrada aqui. Sin migraciones de BD.
//
// ⚠ PERO NO SOLO AQUI. Hay otros DOS sitios que van a la par y que NO dan
// ningun error si se olvidan:
//
//   · `lib/planes.js`  → `PRECIOS_PAIS`. Sin entrada, `getPrecioPlan` se cae a
//     los precios de Colombia y el pais nuevo ve una cifra que no significa
//     nada en su moneda.
//   · `app/registro/RegistroForm.jsx` → `FLAGS`. Sin entrada sale un globo 🌐
//     en vez de su bandera.
//
// Los tres los mantiene alineados `lib/__tests__/paises-completos.test.js`.
//
// EL ORDEN DE ESTE OBJETO ES EL QUE VE EL USUARIO en el desplegable del
// registro: no se ordena alfabeticamente en ningun sitio. Colombia va primera
// a proposito —es el mercado principal— y Estados Unidos cierra por ser el
// unico de fuera de Latinoamerica.

export const COUNTRIES = {
  co: {
    name: 'Colombia',
    currency: 'COP',
    currencySymbol: '$',
    currencyDecimals: 0,
    locale: 'es-CO',
    timezone: 'America/Bogota',
    utcOffset: -5,
    phonePrefix: '+57',
    phoneRegex: /^3\d{9}$/,
    phoneDigits: 10,
    phonePlaceholder: '3001234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{6,12}$/,
    documentLabel: 'Cédula',
    documentAbbr: 'CC',
    documentPlaceholder: '1023456789',
    roundingUnit: 100,
    paymentGateway: 'wompi',
    speechLang: 'es-CO',
    dateFormat: 'DD/MM/YYYY',
  },
  mx: {
    name: 'Mexico',
    currency: 'MXN',
    currencySymbol: '$',
    currencyDecimals: 0,
    locale: 'es-MX',
    timezone: 'America/Mexico_City',
    utcOffset: -6,
    timezones: ['America/Mexico_City', 'America/Cancun', 'America/Chihuahua', 'America/Tijuana'],
    phonePrefix: '+52',
    phoneRegex: /^\d{10}$/,
    phoneDigits: 10,
    phonePlaceholder: '5512345678',
    phoneLabel: 'Celular',
    documentRegex: /^[A-Z]{4}\d{6}[A-Z0-9]{8}$|^\d{10,18}$/i,
    documentLabel: 'CURP / INE',
    documentAbbr: 'CURP',
    documentPlaceholder: 'CURP o número de INE',
    roundingUnit: 10,
    paymentGateway: 'mercadopago',
    speechLang: 'es-MX',
    dateFormat: 'DD/MM/YYYY',
  },
  pe: {
    name: 'Peru',
    currency: 'PEN',
    currencySymbol: 'S/',
    currencyDecimals: 2,
    locale: 'es-PE',
    timezone: 'America/Lima',
    utcOffset: -5,
    phonePrefix: '+51',
    phoneRegex: /^9\d{8}$/,
    phoneDigits: 9,
    phonePlaceholder: '912345678',
    phoneLabel: 'Celular',
    documentRegex: /^\d{8}$/,
    documentLabel: 'DNI',
    documentAbbr: 'DNI',
    documentPlaceholder: '12345678',
    roundingUnit: 1,
    paymentGateway: 'mercadopago',
    speechLang: 'es-PE',
    dateFormat: 'DD/MM/YYYY',
  },
  ec: {
    name: 'Ecuador',
    currency: 'USD',
    currencySymbol: '$',
    currencyDecimals: 2,
    locale: 'es-EC',
    timezone: 'America/Guayaquil',
    utcOffset: -5,
    phonePrefix: '+593',
    phoneRegex: /^0?9\d{8}$/,
    phoneDigits: 10,
    phonePlaceholder: '0991234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{10}$/,
    documentLabel: 'Cédula',
    documentAbbr: 'CI',
    documentPlaceholder: '1712345678',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-EC',
    dateFormat: 'DD/MM/YYYY',
  },
  do: {
    name: 'Republica Dominicana',
    currency: 'DOP',
    currencySymbol: 'RD$',
    currencyDecimals: 0,
    locale: 'es-DO',
    timezone: 'America/Santo_Domingo',
    utcOffset: -4,
    phonePrefix: '+1',
    phoneRegex: /^[89]\d{9}$/,
    phoneDigits: 10,
    phonePlaceholder: '8091234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{11}$/,
    documentLabel: 'Cédula',
    documentAbbr: 'CI',
    documentPlaceholder: '00112345678',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-DO',
    dateFormat: 'DD/MM/YYYY',
  },
  ve: {
    name: 'Venezuela',
    currency: 'USD',
    currencySymbol: '$',
    currencyDecimals: 2,
    locale: 'es-VE',
    timezone: 'America/Caracas',
    utcOffset: -4,
    phonePrefix: '+58',
    phoneRegex: /^(04|4)\d{9,10}$/,
    phoneDigits: 11,
    phonePlaceholder: '04121234567',
    phoneLabel: 'Celular',
    documentRegex: /^[VEJPvejp]-?\d{6,9}$/,
    documentLabel: 'Cédula (V/E/J)',
    documentAbbr: 'CI',
    documentPlaceholder: 'V-12345678',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-VE',
    dateFormat: 'DD/MM/YYYY',
  },
  hn: {
    name: 'Honduras',
    currency: 'HNL',
    currencySymbol: 'L',
    currencyDecimals: 0,
    locale: 'es-HN',
    timezone: 'America/Tegucigalpa',
    utcOffset: -6,
    phonePrefix: '+504',
    phoneRegex: /^\d{8}$/,
    phoneDigits: 8,
    phonePlaceholder: '91234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{4}-?\d{4}-?\d{5}$/,
    documentLabel: 'Identidad',
    documentAbbr: 'ID',
    documentPlaceholder: '0101-1990-12345',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-HN',
    dateFormat: 'DD/MM/YYYY',
  },
  gt: {
    name: 'Guatemala',
    currency: 'GTQ',
    currencySymbol: 'Q',
    currencyDecimals: 0,
    locale: 'es-GT',
    timezone: 'America/Guatemala',
    utcOffset: -6,
    phonePrefix: '+502',
    phoneRegex: /^\d{8}$/,
    phoneDigits: 8,
    phonePlaceholder: '51234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{4,13}$/,
    documentLabel: 'DPI',
    documentAbbr: 'DPI',
    documentPlaceholder: '1234567890101',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-GT',
    dateFormat: 'DD/MM/YYYY',
  },
  sv: {
    name: 'El Salvador',
    currency: 'USD',
    currencySymbol: '$',
    currencyDecimals: 2,
    locale: 'es-SV',
    timezone: 'America/El_Salvador',
    utcOffset: -6,
    phonePrefix: '+503',
    phoneRegex: /^\d{8}$/,
    phoneDigits: 8,
    phonePlaceholder: '71234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{8,9}$/,
    documentLabel: 'DUI',
    documentAbbr: 'DUI',
    documentPlaceholder: '012345678',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-SV',
    dateFormat: 'DD/MM/YYYY',
  },
  ni: {
    name: 'Nicaragua',
    currency: 'NIO',
    currencySymbol: 'C$',
    currencyDecimals: 0,
    locale: 'es-NI',
    timezone: 'America/Managua',
    utcOffset: -6,
    phonePrefix: '+505',
    phoneRegex: /^\d{8}$/,
    phoneDigits: 8,
    phonePlaceholder: '81234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{3}-?\d{6}-?\d{4}[A-Za-z]$/,
    documentLabel: 'Cédula',
    documentAbbr: 'CI',
    documentPlaceholder: '001-010190-0001A',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-NI',
    dateFormat: 'DD/MM/YYYY',
  },
  pa: {
    name: 'Panama',
    currency: 'USD',
    currencySymbol: '$',
    currencyDecimals: 2,
    locale: 'es-PA',
    timezone: 'America/Panama',
    utcOffset: -5,
    phonePrefix: '+507',
    phoneRegex: /^6\d{7}$/,
    phoneDigits: 8,
    phonePlaceholder: '61234567',
    phoneLabel: 'Celular',
    documentRegex: /^(PE|E|N|[23456789]|1[0123]|10)-?\d{1,4}-?\d{1,6}$/i,
    documentLabel: 'Cédula',
    documentAbbr: 'CI',
    documentPlaceholder: '8-123-4567',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-PA',
    dateFormat: 'DD/MM/YYYY',
  },
  cr: {
    name: 'Costa Rica',
    currency: 'CRC',
    currencySymbol: '₡',
    currencyDecimals: 0,
    locale: 'es-CR',
    timezone: 'America/Costa_Rica',
    utcOffset: -6,
    phonePrefix: '+506',
    phoneRegex: /^\d{8}$/,
    phoneDigits: 8,
    phonePlaceholder: '61234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{9,12}$/,
    documentLabel: 'Cédula',
    documentAbbr: 'CI',
    documentPlaceholder: '123456789',
    roundingUnit: 100,
    paymentGateway: 'manual',
    speechLang: 'es-CR',
    dateFormat: 'DD/MM/YYYY',
  },
  // ── EL CONO SUR ───────────────────────────────────────────────────────────
  // Faltaba ENTERO: Argentina, Chile, Bolivia, Paraguay y Uruguay. Lo reportó un
  // colombiano viviendo en Argentina que no encontró su país al registrarse y
  // tuvo que abrir la cuenta con datos de Colombia.
  ar: {
    name: 'Argentina',
    currency: 'ARS',
    currencySymbol: '$',
    currencyDecimals: 0,
    locale: 'es-AR',
    timezone: 'America/Argentina/Buenos_Aires',
    utcOffset: -3,
    // Argentina no cambia de hora, pero sí tiene husos propios en el oeste
    // (Mendoza, San Juan, Salta…). Todos son UTC−3 hoy; van listados porque el
    // selector de zona los muestra y un cobrador de Mendoza espera ver el suyo.
    timezones: ['America/Argentina/Buenos_Aires', 'America/Argentina/Cordoba',
                'America/Argentina/Mendoza', 'America/Argentina/Salta',
                'America/Argentina/Tucuman', 'America/Argentina/Ushuaia'],
    phonePrefix: '+54',
    /* ⚠ EL `9` DE LOS MÓVILES NO VA EN EL NÚMERO. Desde fuera se marca
       +54 9 11 …, pero dentro del país el número es 11 5678-9012: diez dígitos
       empezando por el código de área sin el 0. Se guarda el de diez, que es el
       que la gente escribe y el que WhatsApp acepta con el prefijo delante. */
    phoneRegex: /^\d{10}$/,
    phoneDigits: 10,
    phonePlaceholder: '1156789012',
    phoneLabel: 'Celular',
    // DNI: 7 u 8 dígitos. Se aceptan 6 por los documentos antiguos que aún
    // circulan entre personas mayores.
    documentRegex: /^\d{6,8}$/,
    documentLabel: 'DNI',
    documentAbbr: 'DNI',
    documentPlaceholder: '12345678',
    // A 100, como Colombia: la escala de montos es parecida y es lo que el
    // sistema ya sabe hacer. Una cuota de $12.345 sube a $12.400.
    roundingUnit: 100,
    paymentGateway: 'manual',
    speechLang: 'es-AR',
    dateFormat: 'DD/MM/YYYY',
  },
  cl: {
    name: 'Chile',
    currency: 'CLP',
    currencySymbol: '$',
    currencyDecimals: 0,
    locale: 'es-CL',
    timezone: 'America/Santiago',
    utcOffset: -3,
    timezones: ['America/Santiago', 'Pacific/Easter', 'America/Punta_Arenas'],
    phonePrefix: '+56',
    // Móviles: 9 + ocho dígitos.
    phoneRegex: /^9\d{8}$/,
    phoneDigits: 9,
    phonePlaceholder: '912345678',
    phoneLabel: 'Celular',
    /* El RUT lleva guion y un dígito verificador que puede ser una K
       («12345678-K»), así que el patrón acepta la letra. Sin ella, a uno de
       cada once chilenos le rebotaría su propio documento. */
    documentRegex: /^\d{7,8}-?[\dkK]$/,
    documentLabel: 'RUT',
    documentAbbr: 'RUT',
    documentPlaceholder: '12345678-9',
    roundingUnit: 100,
    paymentGateway: 'manual',
    speechLang: 'es-CL',
    dateFormat: 'DD/MM/YYYY',
  },
  bo: {
    name: 'Bolivia',
    currency: 'BOB',
    /* Con espacio: `formatMoney` pega el símbolo a la cifra sin separación
       —correcto para `$` y `₲`, que son un glifo— y «Bs500.000» se lee mal.
       El espacio va en el símbolo y no en la función porque es propio de este
       país: cambiar `formatMoney` separaría también el peso de su cifra en los
       otros diecisiete. */
    currencySymbol: 'Bs ',
    // El boliviano es de los pocos de la lista donde los centavos se usan de
    // verdad en la calle, pero los préstamos van en unidades enteras.
    currencyDecimals: 0,
    locale: 'es-BO',
    timezone: 'America/La_Paz',
    utcOffset: -4,
    phonePrefix: '+591',
    // Móviles: ocho dígitos que empiezan por 6 o 7.
    phoneRegex: /^[67]\d{7}$/,
    phoneDigits: 8,
    phonePlaceholder: '71234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{5,10}$/,
    documentLabel: 'Carnet de identidad',
    documentAbbr: 'CI',
    documentPlaceholder: '1234567',
    // A 1, no a 100: un boliviano son unos 30 pesos colombianos, así que
    // redondear a 100 Bs sería redondear a 3.000 pesos — se comería la cuota.
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-BO',
    dateFormat: 'DD/MM/YYYY',
  },
  py: {
    name: 'Paraguay',
    currency: 'PYG',
    currencySymbol: '₲',
    // El guaraní no tiene decimales en uso: el céntimo no existe.
    currencyDecimals: 0,
    locale: 'es-PY',
    timezone: 'America/Asuncion',
    utcOffset: -3,
    phonePrefix: '+595',
    // Móviles: 9 + ocho dígitos.
    phoneRegex: /^9\d{8}$/,
    phoneDigits: 9,
    phonePlaceholder: '981234567',
    phoneLabel: 'Celular',
    documentRegex: /^\d{5,8}$/,
    documentLabel: 'Cédula',
    documentAbbr: 'CI',
    documentPlaceholder: '1234567',
    // A 1.000: el guaraní es la moneda con menos valor unitario de la lista
    // (unos 8.000 por dólar) y los billetes empiezan en 2.000.
    roundingUnit: 1000,
    paymentGateway: 'manual',
    speechLang: 'es-PY',
    dateFormat: 'DD/MM/YYYY',
  },
  uy: {
    name: 'Uruguay',
    currency: 'UYU',
    currencySymbol: '$',
    currencyDecimals: 0,
    locale: 'es-UY',
    timezone: 'America/Montevideo',
    utcOffset: -3,
    phonePrefix: '+598',
    // Móviles: 9 + ocho dígitos.
    phoneRegex: /^9\d{7}$/,
    phoneDigits: 8,
    phonePlaceholder: '91234567',
    phoneLabel: 'Celular',
    // La cédula uruguaya lleva dígito verificador, a veces con guion.
    documentRegex: /^\d{6,8}-?\d?$/,
    documentLabel: 'Cédula',
    documentAbbr: 'CI',
    documentPlaceholder: '12345678',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-UY',
    dateFormat: 'DD/MM/YYYY',
  },
  us: {
    name: 'Estados Unidos',
    currency: 'USD',
    currencySymbol: '$',
    currencyDecimals: 2,
    locale: 'es-US',
    timezone: 'America/New_York',
    utcOffset: -5,
    timezones: ['America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles'],
    phonePrefix: '+1',
    phoneRegex: /^\d{10}$/,
    phoneDigits: 10,
    phonePlaceholder: '2125551234',
    phoneLabel: 'Celular',
    documentRegex: /^.{4,20}$/,
    documentLabel: 'ID / Documento',
    documentAbbr: 'ID',
    documentPlaceholder: 'SSN, ITIN o ID estatal',
    roundingUnit: 1,
    paymentGateway: 'manual',
    speechLang: 'es-US',
    dateFormat: 'MM/DD/YYYY',
  },
}

export const COUNTRY_CODES = Object.keys(COUNTRIES)
export const DEFAULT_COUNTRY = 'co'

export function getCountryConfig(country) {
  return COUNTRIES[country] || COUNTRIES[DEFAULT_COUNTRY]
}

export function getCountryList() {
  return COUNTRY_CODES.map((code) => ({
    code,
    name: COUNTRIES[code].name,
  }))
}
